//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembersRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProfileCreation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileCreation()
        {
            this.Relationships = new HashSet<Relationship>();
        }
       

        public long ApplicationId { get; set; }
        public long UserId { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        [DisplayName("First name")]
        public string FirstName { get; set; }

        [DisplayName("Middle name")]
        public string MiddleName { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        [DisplayName("Last name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        [DisplayName("Salutation")]
        public string Suffix { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        [DataType(DataType.Date)]
        [DisplayName("Date of birth")]
        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "The field is required.")]
        public string Gender { get; set; }
        public bool Status { get; set; }


    
        

        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
