//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembersRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Relationship
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public long ApplicationId { get; set; }
        public long RelationId { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ProfileCreation ProfileCreation { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }

        
    }
}
